### ISSUE TITLE
CP4WAIops CR outofSync

### ISSUE THREAD

**Issue by liyanwei93** [cloud-pak-gitops/cp4waiops-gitops#11]
CP4WAIops CR outofSync because of `noi` has been changed by something when deploy `Instalation`

<img width="1272" alt="截屏2021-11-05 下午3 33 49" src="https://user-images.githubusercontent.com/54827063/140485314-d4ccdfea-beb3-48da-9ba0-9b3ec30eda9f.png">

Workaround:

Add ignoreDifferences to application like below:

```
kubectl edit application cp4waiops -n openshift-gitops
```
<img width="567" alt="截屏2021-11-05 下午5 16 08" src="https://user-images.githubusercontent.com/54827063/140487332-3c1dfcd4-78f3-44ff-928d-b042a88cb87b.png">

cc @morningspace @jianh619

**Comment by gyliu513** [comment]
@liyanwei93 is this still a problem?

**Comment by liyanwei93** [comment]
Not anymore
